# Generated by Django 4.1 on 2023-10-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_alter_customuser_email_alter_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.PositiveSmallIntegerField(
                blank="True", choices=[(1, "normal"), (2, "organizacion")], null="True"
            ),
        ),
    ]
