# Generated by Django 4.1 on 2023-10-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0004_alter_customuser_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizacion",
            name="about",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organizacion",
            name="additional_info",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organizacion",
            name="banner",
            field=models.ImageField(blank=True, null=True, upload_to="banners/"),
        ),
        migrations.AddField(
            model_name="organizacion",
            name="footer",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organizacion",
            name="foundation_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="foundation_images/"
            ),
        ),
        migrations.AddField(
            model_name="organizacion",
            name="redirect_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organizacion",
            name="subtitle",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="organizacion",
            name="title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
