# Generated by Django 4.1 on 2023-11-08 04:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0005_organizacion_about_organizacion_additional_info_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                ("url_playlist", models.URLField()),
            ],
        ),
    ]
