# Generated by Django 4.1 on 2023-11-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0006_curso"),
    ]

    operations = [
        migrations.AddField(
            model_name="curso",
            name="banner",
            field=models.ImageField(blank=True, null=True, upload_to="coursesImg/"),
        ),
    ]
