# Generated by Django 4.1 on 2023-11-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0007_curso_banner"),
    ]

    operations = [
        migrations.AddField(
            model_name="curso",
            name="user_name",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
