# Generated by Django 4.1 on 2023-11-08 13:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0006_curso_enlaceyoutube_favorito_curso_enlaces_youtube"),
        ("tasks", "0008_curso_user_name"),
    ]

    operations = []
