# Generated by Django 4.1 on 2023-11-09 03:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0009_alter_curso_url_playlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organizacion",
            name="additional_info",
        ),
    ]
