# Generated by Django 4.1 on 2023-11-09 03:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0010_remove_organizacion_additional_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curso",
            name="url_playlist",
            field=models.URLField(default="", max_length=255),
        ),
    ]
